version: '3.1'

services:
  database: 
    image: mysql:8.0
    container_name: estore_db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3399:3306'
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE} 
    volumes: 
      - ./database/data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d